services:
  - type: web
    name: nemesis-storage-api
    env: node
    buildCommand: npm install
    startCommand: node storage-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    rootDirectory: .
    # Config storage API server
    # Will create directories automatically on startup
