services:
  - type: web
    name: nemesis-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STORAGE_API_URL
        value: http://100.126.96.99:3001  # Your storage server's Tailscale IP
      - key: STORAGE_API_KEY
        sync: false  # We can add an API key later for extra security
    rootDirectory: .
    plan: starter  # We can use the starter plan now since we don't need sudo
    # Note: Additional environment variables must be configured in render.com dashboard:
    # - SAMBA_PASSWORD (if not using inline password in script)
    # - BOT_TOKEN
    # - Other sensitive credentials