services:
  - type: web
    name: nemesis-backend
    env: node
    buildCommand: npm install
    startCommand: apt-get update && apt-get install -y cifs-utils && bash mount-storage.sh && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SAMBA_PASSWORD
        sync: false  # Makes this a secret environment variable
    rootDirectory: .
    # Note: Additional environment variables must be configured in render.com dashboard:
    # - SAMBA_PASSWORD (if not using inline password in script)
    # - BOT_TOKEN
    # - Other sensitive credentials